version: '3'

services:
  webserver:
    container_name: zapfood_webserver
    image: giapcn/zapfood:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - zapfood-network

  # Database service (không bắt buộc, thêm nếu cần)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zapfood
      MYSQL_USER: zapfood_user
      MYSQL_PASSWORD: zapfood_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - zapfood-network

networks:
  zapfood-network:
    driver: bridge

volumes:
  mysql_data: